// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Root": {
    "nextSlide": "Next Slide",
    "prevSlide": "Prev Slide"
  },
  "Header": {
    "search": {
      "toggle": "Delete Search",
      "placeholder": "Search products..."
    },
    "localeSwitcher": {
      "toggle": "Switch Language",
      "id": "Indonesian",
      "en": "English"
    },
    "navigation": {
      "home": "Home",
      "products": "Products",
      "about": "About Us",
      "contact": "Contact Us"
    },
    "auth": {
      "login": "Login"
    },
    "topBar": {
      "phone": "0811-833-164",
      "shippingInfo": "Contact us for deliveries outside Greater Jakarta / outside the island"
    }
  },
  "Login": {
    "close": "Close",
    "title": "Login",
    "register": "Register",
    "phoneLabel": "Phone Number",
    "phonePlaceholder": "Phone Number",
    "passwordLabel": "Password",
    "passwordPlaceholder": "Password",
    "showPassword": "Show password",
    "hidePassword": "Hide password",
    "forgotPassword": "Forgot Password?",
    "processing": "Processing...",
    "submit": "Login",
    "or": "Or",
    "loginWithGoogle": "Continue with Google",
    "loginWithApple": "Continue with Apple"
  },
  "Register": {
    "close": "Close",
    "heroAlt": "Bulky staff in front of shipping containers",
    "title": "Register Now",
    "alreadyHaveAccount": "Already have an account?",
    "login": "Login",
    "registerWithGoogle": "Google",
    "registerWithApple": "Apple",
    "or": "Or",
    "phoneLabel": "Phone Number",
    "phonePlaceholder": "Phone Number",
    "processing": "Processing...",
    "submit": "Register",
    "termsPrefix": "By registering, I agree to the",
    "terms": "Terms & Conditions",
    "and": "and",
    "privacy": "Privacy Policy",
    "errors": {
      "mustAgree": "Please agree to the Terms & Conditions first."
    }
  },
  "Otp": {
    "title": "Account Verification",
    "otpSent": "A 6-digit OTP code has been sent to your WhatsApp number",
    "otpGuide": "Open WhatsApp and enter the code you received.",
    "codeValidPrefix": "The code is valid for",
    "codeValidDuration": "2 minutes",
    "otpGroupAria": "Enter OTP code",
    "otpDigitAria": "Digit {index}",
    "verify": "Verify Code",
    "verifying": "Verifying...",
    "resend": "Resend Code",
    "resending": "Resending...",
    "noCode": "Didn't receive the code?",
    "resendIn": "Resend in",
    "errors": {
      "incomplete": "Please enter the full 6-digit OTP code.",
      "failed": "Verification failed. Please try again."
    }
  },
  "RegisterForm": {
    "title": "Personal Information Form",
    "heroAlt": "Bulky warehouse",
    "nameLabel": "Name",
    "namePlaceholder": "Full name",
    "phoneLabel": "Phone Number",
    "verified": "Verified",
    "phoneVerifiedHint": "This number has been verified via WhatsApp OTP.",
    "emailLabel": "Email",
    "emailPlaceholder": "example@email.com",
    "passwordLabel": "Password",
    "passwordPlaceholder": "Minimum 8 characters",
    "showPassword": "Show password",
    "hidePassword": "Hide password",
    "processing": "Processing...",
    "submit": "Create Account",
    "termsPrefix": "By registering, I agree to",
    "terms": "Terms & Conditions",
    "and": "and",
    "privacy": "Privacy Policy",
    "errors": {
      "nameRequired": "Name is required.",
      "emailRequired": "Email is required.",
      "emailInvalid": "Invalid email format.",
      "passwordRequired": "Password is required.",
      "passwordMin": "Password must be at least 8 characters.",
      "general": "Something went wrong. Please try again."
    }
  },
  "Homepage": {
    "hero": {
      "title": "Build Your Future with Bulky.id",
      "description": "Shop hundreds of liquidation auctions across dozens of categories. All sizes and conditions available.",
      "startNow": "Get Started"
    },
    "recommendation": "Recommendations",
    "seeAllProducts": "View All Products",
    "infoBanner": {
      "title": "Ship Across Indonesia",
      "getNow": "Get It Now",
      "package": "Cargo shipping (self-pickup) or delivery service",
      "payment": "100% Secure Payment Guarantee",
      "cs": "24/7 Dedicated Support",
      "satisfied": "Satisfied Customers"
    },
    "howItWorks": {
      "title": "How Does Bulky.id Work?",
      "description": "We connect retailers, distributors, and logistics partners to create an efficient and profitable inventory management ecosystem. Every step is designed to help businesses maximize the value of every product.",
      "warehouse": "Warehousing",
      "sort": "Sorting",
      "distribution": "Distribution"
    },
    "testimony": {
      "title": "Testimonials",
      "description": "What do customers say about our products and services? See their experiences here."
    }
  },
  "Footer": {
    "company": {
      "description": "Indonesia’s First B2B Recommerce Platform",
      "altCompany": "logo_bulky",
      "srCompany": "Bulky Logo",
      "srInstagram": "Bulky Instagram",
      "srTiktok": "Bulky TikTok"
    },
    "contactUs": {
      "title": "Contact Us",
      "address": "Bulky Warehouse Address",
      "phone": "Bulky Phone Number",
      "email": "Bulky Email"
    },
    "helps": {
      "title": "Help",
      "aboutUs": "About Us",
      "howToBuy": "How to Buy",
      "aboutPayment": "Payment Information",
      "faq": "Frequently Asked Questions",
      "termsCondition": "Terms and Conditions",
      "privacyPolicy": "Privacy Policy"
    },
    "service": {
      "title": "Services",
      "otherProducts": "Other Products",
      "order": "Orders",
      "userProfile": "Profile"
    },
    "getItOn": {
      "title": "Get It On",
      "altPlayStore": "get_it_on_google_play",
      "altAppleStore": "download_on_the_app_store",
      "srPlayStore": "Get it on Google Play",
      "srAppleStore": "Download on the App Store"
    },
    "payment": {
      "title": "Secure Payment",
      "altXendit": "powered_by_xendit"
    },
    "copyright": "Copyright © {date} <Link>Bulky.id</Link>. All Rights Reserved."
  }
};
export default messages;