// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Root": {
    "nextSlide": "Next Slide",
    "prevSlide": "Prev Slide"
  },
  "Header": {
    "search": {
      "toggle": "Delete Search",
      "placeholder": "Search products..."
    },
    "localeSwitcher": {
      "toggle": "Switch Language",
      "id": "Indonesian",
      "en": "English"
    },
    "navigation": {
      "home": "Home",
      "products": "Products",
      "about": "About Us"
    }
  },
  "Homepage": {
    "hero": {
      "title": "Build Your Future with Bulky.id",
      "description": "Shop hundreds of liquidation auctions across dozens of categories. All sizes and conditions available.",
      "startNow": "Get Started"
    },
    "recommendation": "Recommendations",
    "seeAllProducts": "View All Products",
    "infoBanner": {
      "title": "Ship Across Indonesia",
      "getNow": "Get It Now",
      "package": "Cargo shipping (self-pickup) or delivery service",
      "payment": "100% Secure Payment Guarantee",
      "cs": "24/7 Dedicated Support",
      "satisfied": "Satisfied Customers"
    },
    "howItWorks": {
      "title": "How Does Bulky.id Work?",
      "description": "We connect retailers, distributors, and logistics partners to create an efficient and profitable inventory management ecosystem. Every step is designed to help businesses maximize the value of every product.",
      "warehouse": "Warehousing",
      "sort": "Sorting",
      "distribution": "Distribution"
    },
    "testimony": {
      "title": "Testimonials",
      "description": "What do customers say about our products and services? See their experiences here."
    }
  },
  "Footer": {
    "company": {
      "description": "Indonesia’s First B2B Recommerce Platform",
      "altCompany": "logo_bulky",
      "srCompany": "Bulky Logo",
      "srInstagram": "Bulky Instagram",
      "srTiktok": "Bulky TikTok"
    },
    "contactUs": {
      "title": "Contact Us",
      "address": "Bulky Warehouse Address",
      "phone": "Bulky Phone Number",
      "email": "Bulky Email"
    },
    "helps": {
      "title": "Help",
      "aboutUs": "About Us",
      "howToBuy": "How to Buy",
      "aboutPayment": "Payment Information",
      "faq": "Frequently Asked Questions",
      "termsCondition": "Terms and Conditions",
      "privacyPolicy": "Privacy Policy"
    },
    "service": {
      "title": "Services",
      "otherProducts": "Other Products",
      "order": "Orders",
      "userProfile": "Profile"
    },
    "getItOn": {
      "title": "Get It On",
      "altPlayStore": "get_it_on_google_play",
      "altAppleStore": "download_on_the_app_store",
      "srPlayStore": "Get it on Google Play",
      "srAppleStore": "Download on the App Store"
    },
    "payment": {
      "title": "Secure Payment",
      "altXendit": "powered_by_xendit"
    },
    "copyright": "Copyright © {date} <Link>Bulky.id</Link>. All Rights Reserved."
  }
};
export default messages;